### ISSUE TITLE
Handle case of no internet connection

### ISSUE THREAD

**Issue by kantoniak** [kantoniak/discrete-fox#26]
1. Fix exception
2. Make some UI to show users that internet is off

Stacktrace:
```05-01 19:31:18.508 16575-16575/com.kantoniak.discrete_fox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kantoniak.discrete_fox, PID: 16575
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.kantoniak.discrete_fox.game_mechanics.Gameplay.getCurrentQuestion(Gameplay.java:109)
        at com.kantoniak.discrete_fox.game_ui.QuestionSeriesFragment.startGame(QuestionSeriesFragment.java:107)
        at com.kantoniak.discrete_fox.game_ui.QuestionSeriesFragment.onCreateView(QuestionSeriesFragment.java:88)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)```

**Comment by kedzior** [comment]
1. Done with https://github.com/kantoniak/discrete-fox/commit/df506e26406ed46b9495bcec5104f0c6fc50a615

Please add UI for lack of internet

**Comment by kantoniak** [comment]
I can style if need to.

**Comment by kedzior** [comment]
UX need to take a look at the NoConnectionActivity

**Comment by kantoniak** [comment]
Still needs work, mine 😄

**Comment by kantoniak** [comment]
bd1724720140d46c8d791a6535cb13262a6bcfe8
