### ISSUE TITLE
RuntimeException in EasyAR: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by kantoniak** [kantoniak/discrete-fox#30]
Happened when clicked back button from game screen. To invesigate.
```
05-06 16:52:44.246 31199-31199/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kantoniak.discrete_fox, PID: 31199
    java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:2598)
        at cn.easyar.engine.CameraDevice.getSize(CameraDevice.java:297)
        at cn.easyar.CameraDevice.stop(Native Method)
        at com.kantoniak.discrete_fox.ar.EasyARController.stop(EasyARController.java:127)
        at com.kantoniak.discrete_fox.ar.EasyARRenderingDelegate.onBeforeDetachedFromWindow(EasyARRenderingDelegate.java:41)
        at com.kantoniak.discrete_fox.scene.GameSurfaceView.onDetachedFromWindow(GameSurfaceView.java:31)
        at android.view.View.dispatchDetachedFromWindow(View.java:15608)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3507)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6345)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:6315)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:484)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:415)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:168)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4439)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by kantoniak** [comment]
It may be a problem with possibly incorrect tear down of EasyAR.

**Comment by kantoniak** [comment]
Cannot reproduce, we can reopen later.
